version: '3'

services:
  postgres:
    restart: always
    image: postgres
    container_name: headline_db
  web:
    container_name: headline_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/yeet
    ports:
      - "5000:5000"
    depends_on:
      - postgres
